KON-404: Admin role can now edit and resumse processes
aakb/kontrolgruppen-core-bundle pull request #233
Opened 2021-03-05 18:54 UTC by lats1

2021-03-07 09:05 UTC, rimi-itk requested changes

2021-03-07 09:05 UTC, rimi-itk commented on Security/ProcessVoter.php
> +        if ($this->security->isGranted('ROLE_ADMIN')) {
See comment on `ProcessEconomyVoter.php`.

2021-03-08 07:34 UTC, lats1 commented on Security/ProcessEconomyVoter.php
> +        if ($this->security->isGranted('ROLE_ADMIN')) {
I agree. See 2cd8913

2021-03-08 07:34 UTC, lats1 commented on Security/ProcessVoter.php
> +        if ($this->security->isGranted('ROLE_ADMIN')) {
I agree. See 2cd8913

2021-03-08 08:43 UTC, rimi-itk approved these changes

2021-03-08 08:44 UTC, merged